### ISSUE TITLE
readdir() failed (22: Invalid argument)

### ISSUE THREAD

**Issue by stephanvane** [grahamedgecombe/nginx-ct#1]
Hello,

I'd like to use your plugin. Unfortunately I'm getting the following error when starting nginx:

``` bash
nginx: [emerg] readdir() "/usr/local/nginx/conf/ssl/scts" failed (22: Invalid argument)
```

I'm using `nginx-1.9.1` and `openssl-1.0.2a` on ubuntu.

Any idea what could be causing this?

_edit:_ I also tested this with `nginx-1.9.0` (just like the guide [here](http://www.certificate-transparency.org/resources-for-site-owners/nginx)). Didn't help :(

**Comment by grahamedgecombe** [comment]
Can you try again with the latest version? I think commit 6f50f6b might fix this.

**Comment by stephanvane** [comment]
Hi,

It seems to work this time, at least Nginx boots! Thanks for the quick fix

edit: Works perfectly, ev-certificate is showing the green bar in chrome now. thanks again

**Comment by grahamedgecombe** [comment]
Glad it's fully working :)
