### ISSUE TITLE
Failure when using two certificates

### ISSUE THREAD

**Issue by cyanide1959** [grahamedgecombe/nginx-ct#15]
Using the following config:

```
    ssl_ct on;

    ## RSA cert
    ssl_certificate /usr/local/openssl/certs/my.crt;
    ssl_certificate_key /usr/local/openssl/my.key;
    ssl_ct_static_scts /usr/local/openssl/scts/rsa;

    ## ECDSA cert
    ssl_certificate /usr/local/openssl/certs/my.ecdsa.crt;
    ssl_certificate_key /usr/local/openssl/private/my.key;
    ssl_ct_static_scts /usr/local/openssl/scts/ecdsa;
```

We see the following:

>  \# nginx -t
> nginx: [emerg] "ssl_ct_static_scts" directive is duplicate in /usr/local/etc/nginx/site.conf:27
> nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

> \# nginx -V
> nginx version: nginx/1.11.8
> built with OpenSSL 1.0.2j  26 Sep 2016
> TLS SNI support enabled
> configure arguments: --prefix=/usr/local/etc/nginx --with-cc-opt='-I /usr/local/include' --with-ld-opt='-L /usr/local/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --sbin-path=/usr/local/sbin/nginx --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --user=www --group=www --modules-path=/usr/local/libexec/nginx --with-file-aio --with-ipv6 --http-client-body-temp-path=/var/tmp/nginx/client_body_temp --http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp --http-proxy-temp-path=/var/tmp/nginx/proxy_temp --http-scgi-temp-path=/var/tmp/nginx/scgi_temp --http-uwsgi-temp-path=/var/tmp/nginx/uwsgi_temp --http-log-path=/var/log/nginx/access.log --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx_cache_purge-2.3 --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/nginx-ct-f3cad5e --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/echo-nginx-module-46334b3 --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/headers-more-nginx-module-84241e4 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx-fancyindex-0.3.6 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/nginx-http-footer-filter-1.2.2 --with-http_realip_module --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx_http_redis-0.3.8 --with-http_sub_module --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx_devel_kit-0.3.0 --with-pcre --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/redis2-nginx-module-0.12 --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/set-misc-nginx-module-f808ef4 --add-module=/wrkdirs/usr/ports/www/nginx-devel/work/srcache-nginx-module-0.30 --with-http_v2_module --with-http_ssl_module --add-dynamic-module=/wrkdirs/usr/ports/www/nginx-devel/work/ngx_brotli-ada972b

**Comment by grahamedgecombe** [comment]
It looks like you are using f3cad5e (v1.2.0), but support for multiple SSL certificates was added in v1.3.0.

**Comment by cyanide1959** [comment]
I just saw that. The version in FreeBSD ports is indeed out of date. I rebuilt with current version and the issue resolved. I'm about to submit a patch. 

Sorry for the noise.
