### ISSUE TITLE
Using ngx_mail_ssl_ct_module

### ISSUE THREAD

**Issue by fmunteanu** [grahamedgecombe/nginx-ct#33]
Is ngx_ssl_ct_module required to be loaded before ngx_mail_ssl_ct_module? I intend to use only ngx_mail_ssl_ct_module and skip ngx_http_ssl_ct_module.

**Comment by grahamedgecombe** [comment]
Yes, ngx_ssl_ct_module is always required and must be loaded first. (Though I think the ngx_module_order stuff might take care of that for you.)

**Comment by fmunteanu** [comment]
Thanks @grahamedgecombe, I thought so also and added into each package the file. Example:
```
$ cat /usr/share/nginx/modules/mod-stream.conf
load_module "/usr/lib64/nginx/modules/ngx_stream_module.so";
load_module "/usr/lib64/nginx/modules/ngx_stream_geoip_module.so";
load_module "/usr/lib64/nginx/modules/ngx_ssl_ct_module.so";
load_module "/usr/lib64/nginx/modules/ngx_stream_ssl_ct_module.so";
```
So I load first ngx_ssl_ct_module.so, then ngx_stream_ssl_ct_module.so. I made RPM packages for CentOS 7.4:
```
$ yum --enablerepo=axivo -q list ct-submit nginx-mod-http-ssl-ct
Available Packages
ct-submit.x86_64                      1.1.2-1.el7              axivo
nginx-mod-http-ssl-ct.x86_64          1:1.13.5-1.el7           axivo
```
Thank you for the great work.
