### ISSUE TITLE
What is sct files

### ISSUE THREAD

**Issue by giolazzareschi** [grahamedgecombe/nginx-ct#37]
Hi,

I am currently using this nginx

- nginx version: nginx/1.10.3 (Ubuntu)

And recompiled it with the "--add-module=/path/to/nginx-ct"

Now I'm configuring my nginx.conf file. I know that can be a silly question but I am not experienced with nginx enviroment and compilation. I am trying to put this on my nginx.conf file:

ssl_ct on;
ssl_ct_static_scts /path/to/sct/dir;

questions: 

- where is the SCT directory
- what is the SCT files.
- I already have "ssl on" directive, should I replace it for the "ssl_ct on" ?

Sorry for the very dummy questions but any help will be appreciated.

**Comment by Knight1** [comment]
Short question: Do you use Let‘s Encrypt? 

Because Let‘s Encrypt is currently submitting the signed certificate to the logs and give you a certificate with the act embedded. So you might not need this module if your current certs have the sct‘s embedded. If you do not know how to do this let me know :) 

More infos: https://www.certificate-transparency.org/how-ct-works

**Comment by giolazzareschi** [comment]
Hi @Knight1 

Thanks for the reply and for the observation. 

Yes, I do use Let's Encrypt with certbot.

I did use this website https://cryptoreport.websecurity.symantec.com/checker/ to verify my CT and it tells me 

- Certificate Transparency: Not embedded in certificate

But how can I check if my certificate already have the sct's embedded?

Should I just renew it?

**Comment by Knight1** [comment]
You can verify it by the issue date. If it is after 29 March it should have it; if not you can renew it if you want it. Do you want to deploy expect-ct or what is your intention behind it?

https://community.letsencrypt.org/t/signed-certificate-timestamps-embedded-in-certificates/57187/3

**Comment by giolazzareschi** [comment]
I understand.

Well, currently my webapp product is running in a lot of customers that are instructed to use Chrome for better experience and I do not want them to face any kind of "insecure website" or something.

I just knew about this CT a few days ago and I'm trying make everything works fine. But I think on the next renewall that's should be fine.

Thanks a lot for your help and attention. Much appreciated.
