### ISSUE TITLE
CT support for other nginx modules, not just http

### ISSUE THREAD

**Issue by espadolini** [grahamedgecombe/nginx-ct#4]
How hard would it be to adapt the current module to also cooperate with `ngx_stream_ssl_module` or `ngx_mail_ssl_module`? Would it lead to too much code duplication?

**Comment by grahamedgecombe** [comment]
Added support to this for master. There's still more code duplication than I'd like though :(

**Comment by grahamedgecombe** [comment]
Tagged v1.1.0 which includes this.
