### ISSUE TITLE
nginx 1.11.0 multiple certificate support

### ISSUE THREAD

**Issue by grahamedgecombe** [grahamedgecombe/nginx-ct#9]

**Comment by qgy18** [comment]
Looking forward to this.

**Comment by grahamedgecombe** [comment]
Added in 08c84f78532bef26c83307431928b691a5773e0e

**Comment by ghost** [comment]
@grahamedgecombe How to use this new feature? Put all the file together or in seperated directories?

**Comment by grahamedgecombe** [comment]
One directory per certificate. Each `ssl_certificate` directive needs a corresponding `ssl_ct_static_scts` directive pointing to that dir.

The readme has an example (the big code block near the bottom).

**Comment by ghost** [comment]
@grahamedgecombe That is good!
